DROP TABLE IF EXISTS user;
CREATE TABLE user (
    id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY , 
    username        VARCHAR(255) UNIQUE,
    password        VARCHAR(255),
    email       	VARCHAR(255) UNIQUE,
    active        BOOLEAN
);


INSERT INTO user ( username,password,email,active ) 
VALUES ( 'admin', 'admin','mynamestillisi@gmail.com','false');

INSERT INTO user ( username,password,email,active ) 
VALUES ( '111', '111','410145576@qq.com','false');
